In [18]:
import pandas as pd
from IPython.display import display

df = pd.read_csv("gsm8k_llama3.1-8b-instant.csv")
display(df)

accuracy = df["is_correct"].mean()

print("Accuracy:", accuracy)

,question_id,model,correct_answer,model_answer,is_correct,timestamp
0,0,llama-3.1-8b-instant,18,18.0,False,2026-03-01 09:48:56.503461
1,1,llama-3.1-8b-instant,3,3.0,True,2026-03-01 09:48:56.689760
2,2,llama-3.1-8b-instant,70000,0.0,False,2026-03-01 09:48:57.125370
3,3,llama-3.1-8b-instant,540,540.0,True,2026-03-01 09:48:57.258753
4,4,llama-3.1-8b-instant,20,20.0,True,2026-03-01 09:48:57.439938
5,5,llama-3.1-8b-instant,64,64.0,True,2026-03-01 09:48:57.667710
6,6,llama-3.1-8b-instant,260,260.0,True,2026-03-01 09:48:57.792151
7,7,llama-3.1-8b-instant,160,140.0,False,2026-03-01 09:48:58.058894
8,8,llama-3.1-8b-instant,45,315.0,False,2026-03-01 09:48:58.409308
9,9,llama-3.1-8b-instant,460,460.0,True,2026-03-01 09:48:58.533083

Accuracy: 0.6

In [19]:
df = pd.read_csv("gsm8k_llama3.3-70b-versatile.csv")
display(df)
accuracy = df["is_correct"].mean()

print("Accuracy:", accuracy)

,question_id,model,correct_answer,model_answer,is_correct,timestamp
0,0,llama-3.3-70b-versatile,18,28.0,False,2026-03-01 10:06:46.446760
1,1,llama-3.3-70b-versatile,3,3.0,True,2026-03-01 10:06:46.551894
2,2,llama-3.3-70b-versatile,70000,0.0,False,2026-03-01 10:06:46.657311
3,3,llama-3.3-70b-versatile,540,540.0,True,2026-03-01 10:06:46.805391
4,4,llama-3.3-70b-versatile,20,10.0,False,2026-03-01 10:06:46.922505
5,5,llama-3.3-70b-versatile,64,64.0,True,2026-03-01 10:06:47.306563
6,6,llama-3.3-70b-versatile,260,72.0,False,2026-03-01 10:06:47.443139
7,7,llama-3.3-70b-versatile,160,160.0,False,2026-03-01 10:06:47.911453
8,8,llama-3.3-70b-versatile,45,45.0,True,2026-03-01 10:06:49.524596
9,9,llama-3.3-70b-versatile,460,475.0,False,2026-03-01 10:06:49.672251

Accuracy: 0.4

In [20]:
df = pd.read_csv("gsm8k_openai_gpt-oss-120b.csv")
display(df)

accuracy = df["is_correct"].mean()

print("Accuracy:", accuracy)

,question_id,model,correct_answer,model_answer,is_correct,timestamp
0,0,openai/gpt-oss-120b,18,18,True,2026-03-01 16:38:04.501176
1,1,openai/gpt-oss-120b,3,3,True,2026-03-01 16:38:04.755224
2,2,openai/gpt-oss-120b,70000,70000,True,2026-03-01 16:38:05.942918
3,3,openai/gpt-oss-120b,540,540,True,2026-03-01 16:38:06.196482
4,4,openai/gpt-oss-120b,20,20,True,2026-03-01 16:38:06.464381
5,5,openai/gpt-oss-120b,64,64,True,2026-03-01 16:38:06.817687
6,6,openai/gpt-oss-120b,260,260,True,2026-03-01 16:38:07.016328
7,7,openai/gpt-oss-120b,160,160,True,2026-03-01 16:38:07.640129
8,8,openai/gpt-oss-120b,45,45,True,2026-03-01 16:38:08.312291
9,9,openai/gpt-oss-120b,460,460,True,2026-03-01 16:38:08.639573

Accuracy: 1.0

In [23]:
results_df = pd.read_csv("rubric_gsm8k_openai_gpt-oss-120b.csv")
display(results_df)

,question_id,model,score,feedback,timestamp
0,0,openai/gpt-oss-120b,10,Correct answer and correct arithmetic reasoning; solution is clear and well-explained.,2026-03-02 10:40:32.738697
1,1,openai/gpt-oss-120b,10,Correct answer (3 bolts) with appropriate reasoning (half of 2 is 1) and clear explanation.,2026-03-02 10:40:33.344389
2,2,openai/gpt-oss-120b,10,"All calculations are correct and the reasoning is clearly presented, earning full credit.",2026-03-02 10:40:34.044998
3,3,openai/gpt-oss-120b,10,Correct answer (540 m) with appropriate reasoning steps and clear explanation.,2026-03-02 10:40:34.562177
4,4,openai/gpt-oss-120b,10,"Correct final answer (20 cups) with accurate calculations and clear, logical steps.",2026-03-02 10:40:34.947362
5,5,openai/gpt-oss-120b,10,"The solution correctly computes the discounted price, counts the number of discounted and full-price glasses, and adds them to get $64. The reasoning is accurate and clearly explained.",2026-03-02 10:40:35.600430
6,6,openai/gpt-oss-120b,10,"All calculations are correct, reasoning is logical and clearly presented.",2026-03-02 10:40:35.959618
7,7,openai/gpt-oss-120b,10,Correct final answer (160 minutes) with accurate calculations and clear step-by-step reasoning.,2026-03-02 10:40:36.597347
8,8,openai/gpt-oss-120b,10,Correct final answer (45 miles). All reasoning steps are accurate and logically follow the problem. Explanation is clear and includes appropriate intermediate calculations.,2026-03-02 10:40:37.444713
9,9,openai/gpt-oss-120b,10,"All calculations are correct, reasoning is complete, and the explanation is clear and well-structured.",2026-03-02 10:40:37.957588

In [24]:
results_df = pd.read_csv("rubric_gsm8k_llama-3.1-8b-instant.csv")
display(results_df)

,question_id,model,score,feedback,timestamp
0,0,llama-3.1-8b-instant,8,"Correct final answer, but the student could improve their reasoning steps by explaining why they subtracted 3 and 4 from 16, and what the remainder represents. Clarity and explanation could also be improved by using more descriptive language and possibly adding a sentence to explain the context of the problem.",2026-03-02 10:51:37.327396
1,1,llama-3.1-8b-instant,6,"The student correctly calculates the amount of white fiber and adds it to the amount of blue fiber, but the explanation is unclear and the student seems to misunderstand the question, as the final answer is not the total amount of bolts of fabric, but rather the total amount of fabric.",2026-03-02 10:51:37.551321
2,2,llama-3.1-8b-instant,9,"Correct final answer, but the student incorrectly states that the value of the house increased by 150% of the original price, when in fact it increased by 150% of the original price plus the repairs. The student's reasoning steps are mostly correct, but could be clarified. The explanation is clear and easy to follow.",2026-03-02 10:51:37.820434
3,3,llama-3.1-8b-instant,9,"Correct final answer, but the student could improve their reasoning steps by explaining why they multiplied the number of sprints by the number of times they run them, and also by explaining why they then multiplied the result by the distance of each sprint.",2026-03-02 10:51:38.018357
4,4,llama-3.1-8b-instant,9,"Correct final answer, but the student could improve their reasoning steps by explicitly stating that the total daily feed required is 60 cups, and then subtracting the morning and afternoon feed from this total to find the final meal feed.",2026-03-02 10:51:38.219530
5,5,llama-3.1-8b-instant,9,"Correct final answer, but the student incorrectly assumes that the cheaper glasses are the ones that are bought in pairs. The correct interpretation is that every second glass is cheaper, not that the cheaper glasses are bought in pairs. However, the student's solution still leads to the correct final answer.",2026-03-02 10:51:38.441277
6,6,llama-3.1-8b-instant,10,The student's solution is correct and well-explained. They accurately calculated the number of sheep in each city and then added them together to find the total.,2026-03-02 10:51:38.673070
7,7,llama-3.1-8b-instant,9,"Correct final answer, but the student incorrectly added the time to download 40% of the file. The correct calculation should be the time to download the whole file (100 minutes) plus the time to download the remaining 60% of the file (120 minutes) plus the time to wait for Windows to update (20 minutes).",2026-03-02 10:51:38.867182
8,8,llama-3.1-8b-instant,9,"Correct final answer, but the student incorrectly calculated the distance driven in the first 2 hours of the return trip. The student should have calculated the distance driven in the first 2 hours as 0 miles since they were in standstill traffic, not 30 miles as implied by the 30mph speed for 0.5 hours.",2026-03-02 10:51:39.194683
9,9,llama-3.1-8b-instant,9,"Correct final answer, but the student could improve clarity and explanation of the overtime pay calculation and the total earnings calculation.",2026-03-02 10:51:39.367668

In [25]:
results_df = pd.read_csv("rubric_gsm8k_llama-3.3-70b-versatile.csv")
display(results_df)

,question_id,model,score,feedback,timestamp
0,0,llama-3.3-70b-versatile,10,"The student provided a correct final answer with clear and logical reasoning steps, explaining the calculation process thoroughly.",2026-03-02 10:52:29.762196
1,1,llama-3.3-70b-versatile,10,"The student correctly calculated the amount of white fiber as half of the blue fiber, which is 1 bolt, and then added it to the 2 bolts of blue fiber to get a total of 3 bolts.",2026-03-02 10:52:30.008546
2,2,llama-3.3-70b-versatile,10,"The student's solution is correct, with proper reasoning steps and clear explanations.",2026-03-02 10:52:30.476838
3,3,llama-3.3-70b-versatile,10,"Correct final answer, clear reasoning steps, and well-explained solution.",2026-03-02 10:52:30.713432
4,4,llama-3.3-70b-versatile,10,"The student's solution is correct, with proper reasoning and clear explanation.",2026-03-02 10:52:30.912391
5,5,llama-3.3-70b-versatile,10,"The student's solution is correct, with proper reasoning steps and clear explanations.",2026-03-02 10:52:31.162785
6,6,llama-3.3-70b-versatile,10,The student provided a clear and correct solution with proper reasoning steps.,2026-03-02 10:52:31.400658
7,7,llama-3.3-70b-versatile,10,"The student's solution is correct, with proper reasoning steps and clear explanations.",2026-03-02 10:52:31.695981
8,8,llama-3.3-70b-versatile,10,"The student's solution is correct, with proper reasoning steps and clear explanations.",2026-03-02 10:52:31.900857
9,9,llama-3.3-70b-versatile,10,"The student's solution is correct, with proper reasoning steps and clear explanations, leading to the correct final answer of $460.",2026-03-02 10:52:32.200424